# Generated by Django 6.1.1 on 2026-09-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='cooperating_agencies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='implementing_unit',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='is_continuing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='research_priority_area',
            field=models.CharField(blank=True, choices=[('science_math', 'Science and Mathematics'), ('education_teacher_training', "Education and Teacher's Training"), ('health', 'Health and Health Profession'), ('ict', 'Information and Communication Tech.'), ('engineering', 'Engineering'), ('agriculture_fisheries', 'Agriculture and Fisheries'), ('environmental_science', 'Environmental Science'), ('social_sciences_humanities', 'Social Sciences and Humanities')], max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='research_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Research'), ('applied', 'Applied Research')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='research_typology',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='sdgs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, choices=[('agriculture_fisheries', 'Agriculture/Fisheries'), ('education', 'Education'), ('community_development', 'Community Development'), ('information_tech', 'Information Tech.'), ('politics', 'Politics'), ('others', 'Others')], max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='sector_other',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
