# Generated by Django 6.1.1 on 2026-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_impacts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_approved_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proposal_submitted_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reviewing_body',
            field=models.CharField(blank=True, help_text='e.g. ITRC, ETRC, CRC', max_length=150),
        ),
    ]
