# Generated by Django 6.1.1 on 2026-09-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0004_projectstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workplanmilestone',
            name='deliverable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workplanmilestone',
            name='objective',
            field=models.TextField(blank=True, help_text='Which project objective this activity serves'),
        ),
        migrations.AddField(
            model_name='workplanmilestone',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milestones_responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workplanmilestone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
