# Generated by Django 6.1.1 on 2026-09-26 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_sector_to_sectors(apps, schema_editor):
    Project = apps.get_model("research_projects", "Project")
    for project in Project.objects.exclude(sector=""):
        project.sectors = [project.sector]
        project.save(update_fields=["sectors"])


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0005_workplanmilestone_deliverable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_by_president',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='college',
            field=models.CharField(blank=True, help_text='College Unit (Annex A endorsement page)', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='continuing_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year 2, Year 3, ... when continuing', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='endorsed_by_dean',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='endorsed_by_dean_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='methodology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='monitoring_evaluation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='noted_by_rds_director',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='noted_by_rds_director_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_by_campus_director',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_by_campus_director_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_by_vprde',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='recommended_by_vprde_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='socio_economic_significance',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ProjectTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(choices=[('co_leader', 'Co-Project Leader'), ('member', 'Team Member')], default='member', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='research_projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_beneficiaries', to='research_projects.project')),
            ],
        ),
        migrations.RunPython(copy_sector_to_sectors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='project',
            name='sector',
        ),
    ]
