# Generated by Django 6.1.1 on 2026-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0008_project_endorser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
