# Generated by Django 6.1.1 on 2026-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_projects', '0012_rei_thrust_dash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndorserChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designation', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
