# Generated by Django 6.1.1 on 2026-09-22 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUseDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=150)),
                ('purpose', models.CharField(help_text='e.g. grammar editing, data analysis, literature summarization', max_length=300)),
                ('extent', models.TextField(help_text='Description of how and where AI was used in the work')),
                ('declared_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_use_declarations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_use_declarations', to='research_projects.project')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_use_declarations', to='research_projects.study')),
            ],
        ),
        migrations.CreateModel(
            name='ConflictOfInterestDisclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mitigation_measures', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('disclosed', 'Disclosed'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='disclosed', max_length=20)),
                ('disclosed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discloser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coi_disclosures', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coi_disclosures', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coi_disclosures_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EthicsReviewReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_body', models.CharField(choices=[('trc', 'Technical Review Committee'), ('ethics_review_board', 'Ethics Review Board'), ('iacuc', 'Institutional Animal Care and Use Committee')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('conditional', 'Conditionally Approved'), ('revision_required', 'Revision Required'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethics_reviews', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ethics_reviews_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethics_reviews', to='research_projects.study')),
            ],
        ),
        migrations.CreateModel(
            name='MisconductCaseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, help_text='Used when the subject is not a system user, e.g. a student', max_length=150)),
                ('case_type', models.CharField(choices=[('plagiarism', 'Plagiarism'), ('fabrication', 'Fabrication'), ('falsification', 'Falsification'), ('other', 'Other')], max_length=20)),
                ('referred_to', models.CharField(help_text='e.g. Dean, Research Chairperson', max_length=150)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('upheld', 'Upheld'), ('dismissed', 'Dismissed')], default='reported', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('reported_on', models.DateField()),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconduct_cases', to='research_projects.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='misconduct_cases_reported', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='misconduct_cases_against', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarityCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('published_article', 'Article for Publication'), ('thesis_dissertation', 'Thesis/Dissertation'), ('other', 'Other')], max_length=30)),
                ('document_title', models.CharField(blank=True, max_length=300)),
                ('similarity_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_within_threshold', models.BooleanField(default=True, editable=False)),
                ('software_used', models.CharField(blank=True, max_length=100)),
                ('checked_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_checks', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='similarity_checks_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='similarity_checks', to='research_projects.study')),
            ],
        ),
    ]
