# Generated by Django 6.1.1 on 2026-09-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusedeclaration',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiusedeclaration',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conflictofinterestdisclosure',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflictofinterestdisclosure',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethicsreviewreference',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ethicsreviewreference',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='similaritycheckrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='similaritycheckrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ethicsreviewreference',
            name='review_body',
            field=models.CharField(choices=[('trc', 'Technical Review Committee'), ('integrity_review', 'Research Integrity Review'), ('external_review', 'External Review Body')], max_length=30),
        ),
    ]
