# Generated by Django 6.1.1 on 2026-09-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_compliancerequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusedeclaration',
            name='ai_content_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
