# Generated by Django 6.1.1 on 2026-09-22 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('toe', 'Terms of Engagement'), ('lib', 'Line-Item Budget'), ('work_plan', 'Work Plan'), ('midterm_report', 'Midterm Report'), ('terminal_report', 'Terminal Report'), ('accomplishment_report', 'Accomplishment Report'), ('thesis', 'Thesis'), ('dissertation', 'Dissertation'), ('dataset', 'Research Dataset'), ('manuscript', 'Manuscript'), ('other', 'Other')], max_length=30)),
                ('stage', models.CharField(blank=True, choices=[('inception', 'Inception'), ('midterm', 'Midterm'), ('terminal', 'Terminal'), ('post_completion', 'Post-Completion')], max_length=20)),
                ('version_number', models.PositiveIntegerField(editable=False)),
                ('is_current', models.BooleanField(default=True, editable=False)),
                ('storage_path', models.CharField(editable=False, max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('retention_until', models.DateField(editable=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research_projects.project')),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='research_projects.study')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
