# Generated by Django 6.1.1 on 2026-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sensitivity',
            field=models.CharField(choices=[('project_team', 'Project Team'), ('financial', 'Financial'), ('restricted', 'Restricted')], default='project_team', max_length=20),
        ),
    ]
