# Generated by Django 6.1.1 on 2026-10-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0004_documentshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('toe', 'Terms of Engagement'), ('lib', 'Line-Item Budget'), ('work_plan', 'Work Plan'), ('midterm_report', 'Midterm Report'), ('terminal_report', 'Terminal Report'), ('accomplishment_report', 'Accomplishment Report'), ('proposal_form', 'Research Proposal Form (SF-018)'), ('thesis', 'Thesis'), ('dissertation', 'Dissertation'), ('dataset', 'Research Dataset'), ('manuscript', 'Manuscript'), ('other', 'Other')], max_length=30),
        ),
    ]
