# Generated by Django 6.1.1 on 2026-09-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_taskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
