# Generated by Django 6.1.1 on 2026-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_projectassignment_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('for_review', 'For Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='new_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('for_review', 'For Review'), ('done', 'Done'), ('blocked', 'Blocked')], max_length=20),
        ),
    ]
