# Generated by Django 6.1.1 on 2026-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_task_completed_at_task_started_at_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours worked since the last update', max_digits=6),
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='kind',
            field=models.CharField(choices=[('update', 'Update'), ('comment', 'Comment'), ('blocker', 'Blocker'), ('completion', 'Completion')], default='update', max_length=20),
        ),
    ]
