# Generated by Django 6.1.1 on 2026-10-02 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_task_tags_taskdeliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(blank=True, help_text='% of the task completed as of this update', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
