# Generated by Django 6.1.1 on 2026-10-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_task_update_progress'),
        ('research_projects', '0008_project_endorser'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='research_projects.workplanmilestone'),
        ),
    ]
