# Generated by Django 6.1.1 on 2026-09-23 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('completed_projects', 'Completed Projects'), ('publications', 'Publications'), ('ip_disclosures', 'IP Disclosures'), ('budget_utilization_pct', 'Budget Utilization %')], max_length=30)),
                ('campus', models.CharField(blank=True, help_text='Blank = institution-wide', max_length=100)),
                ('target_year', models.PositiveIntegerField()),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planning_targets_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metric', 'campus', 'target_year'), name='unique_planning_target')],
            },
        ),
    ]
