# Generated by Django 6.1.1 on 2026-09-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='tier',
        ),
        migrations.AddField(
            model_name='user',
            name='registration_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_by', to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_pending_role',
            field=models.BooleanField(default=True),
        ),
    ]
