# Generated by Django 6.1.1 on 2026-09-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, help_text='Office/department (college, unit, campus office)', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Plantilla/academic position, e.g. Associate Professor II', max_length=150),
        ),
    ]
