# Generated by Django 6.1.1 on 2026-09-26 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_widen_view_users_by_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, help_text='e.g. Study Leader (Acting)', max_length=150)),
                ('coverage', models.TextField(blank=True, help_text='What the replacement covers')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('basis', models.CharField(blank=True, help_text='Office order / memo number', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Set when ended early or the user is reactivated', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements_created', to=settings.AUTH_USER_MODEL)),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acting_for', to=settings.AUTH_USER_MODEL)),
                ('suspended_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
