# Generated by Django 6.1.1 on 2026-09-23 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('appendix_e', 'Appendix E - Midterm Progress Report'), ('appendix_f', 'Appendix F - Terminal Report'), ('appendix_g', 'Appendix G - R&D Accomplishment Report'), ('project_list', 'Custom Filtered Project List')], max_length=30)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF'), ('docx', 'DOCX')], max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
