# Generated by Django 6.1.1 on 2026-09-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreportlog',
            name='report_type',
            field=models.CharField(choices=[('appendix_e', 'Appendix E - Midterm Progress Report'), ('appendix_f', 'Appendix F - Terminal Report'), ('appendix_g', 'Appendix G - R&D Accomplishment Report'), ('project_list', 'Custom Filtered Project List'), ('financial', 'Financial / Procurement Report'), ('compliance', 'Compliance Report'), ('personnel', 'Personnel and Task Report'), ('outputs', 'Research Outputs (6Ps) Report')], max_length=30),
        ),
    ]
