from django.urls import path
from .views import (
    ProgramListCreateView,
    ProgramDetailView,
    ProjectListCreateView,
    ProjectDetailView,
    ProjectStatusHistoryView,
    ProjectCodeAvailableView,
    ProjectLibView,
    ProjectImportTemplateView,
    ProjectImportView,
    TeamMemberListCreateView,
    TeamMemberDetailView,
    BeneficiaryListCreateView,
    EndorserListCreateView,
    EndorserDetailView,
    BeneficiaryDetailView,
    StudyListCreateView,
    StudyDetailView,
    MilestoneListCreateView,
    MilestoneDetailView,
)

urlpatterns = [
    path("programs/", ProgramListCreateView.as_view()),
    path("programs/<int:pk>/", ProgramDetailView.as_view()),
    path("projects/", ProjectListCreateView.as_view()),
    path("projects/code-available/", ProjectCodeAvailableView.as_view()),
    path("projects/import-template/", ProjectImportTemplateView.as_view()),
    path("projects/import/", ProjectImportView.as_view()),
    path("projects/<int:pk>/", ProjectDetailView.as_view()),
    path("projects/<int:pk>/lib/", ProjectLibView.as_view()),
    path("project-team/", TeamMemberListCreateView.as_view()),
    path("project-team/<int:pk>/", TeamMemberDetailView.as_view()),
    path("project-endorsers/", EndorserListCreateView.as_view()),
    path("project-endorsers/<int:pk>/", EndorserDetailView.as_view()),
    path("target-beneficiaries/", BeneficiaryListCreateView.as_view()),
    path("target-beneficiaries/<int:pk>/", BeneficiaryDetailView.as_view()),
    path("projects/<int:pk>/status-history/", ProjectStatusHistoryView.as_view()),
    path("studies/", StudyListCreateView.as_view()),
    path("studies/<int:pk>/", StudyDetailView.as_view()),
    path("milestones/", MilestoneListCreateView.as_view()),
    path("milestones/<int:pk>/", MilestoneDetailView.as_view()),
]