# Generated by Django 6.1.1 on 2026-09-22 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_lib', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRealignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_item_category', models.CharField(blank=True, choices=[('ps', 'Personal Services'), ('mooe', 'Maintenance and Other Operating Expenses'), ('co', 'Capital Outlay')], max_length=10)),
                ('new_item_description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tier', models.CharField(choices=[('minor', 'Minor (<=33% of source item)'), ('major', 'Major (33-100% of source item)'), ('bor', 'Requires Board of Regents Approval')], editable=False, max_length=10)),
                ('status', models.CharField(choices=[('implemented', 'Implemented'), ('pending_approval', 'Pending University Administration Approval'), ('approved', 'Approved'), ('pending_bor', 'Pending Board of Regents Approval'), ('bor_approved', 'Board of Regents Approved'), ('rejected', 'Rejected')], default='implemented', max_length=20)),
                ('justification', models.TextField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bor_resolution_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realignments_from', to='budget_lib.lineitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realignments_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realignments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('to_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='realignments_to', to='budget_lib.lineitem')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_number', models.CharField(blank=True, help_text='OR/voucher number', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('disbursed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='budget_lib.lineitem')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
