# Generated by Django 6.1.1 on 2026-09-24 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
        ('financial_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='payee',
            field=models.CharField(blank=True, help_text='Payee/vendor', max_length=200),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='supporting_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='document_management.document'),
        ),
    ]
