# Generated by Django 6.1.1 on 2026-09-24 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_lib', '0002_lineitem_fiscal_year_lineitem_funding_source_and_more'),
        ('financial_monitoring', '0002_disbursement_payee_disbursement_supporting_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processing_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests', to='budget_lib.lineitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procurement_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
