# Generated by Django 6.1.1 on 2026-10-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_monitoring', '0003_procurementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrealignment',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
