# Generated by Django 6.1.1 on 2026-09-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_management', '0001_initial'),
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_reports_certified', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_reports', to='document_management.document')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_report', to='research_projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminal_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MidtermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_year', models.PositiveIntegerField(default=1, help_text='Which year of a multi-year project this covers')),
                ('narrative', models.TextField(blank=True)),
                ('expenditure_summary', models.TextField(blank=True, help_text='Summary of expenditures per quarter')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midterm_reports', to='document_management.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reports', to='research_projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='midterm_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'project_year'), name='unique_project_midterm_year')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='First day of the month this report covers')),
                ('narrative', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_reports', to='document_management.document')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='research_projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
                'constraints': [models.UniqueConstraint(fields=('project', 'period'), name='unique_project_monthly_report_period')],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_year', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('panel_members', models.TextField(blank=True, help_text='Names/roles of panel members, incl. any external member')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('conditional', 'Conditional'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluations_recorded', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='research_projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'project_year'), name='unique_project_evaluation_year')],
            },
        ),
        migrations.CreateModel(
            name='RenewalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_year', models.PositiveIntegerField(help_text='The upcoming project-year being applied for')),
                ('underspend_justification', models.TextField(blank=True, help_text='Reasonable explanation for unspent funds, if budget usage is below 70%')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_applications_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_applications', to='research_projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_applications_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'application_year'), name='unique_project_renewal_year')],
            },
        ),
    ]
