# Generated by Django 6.1.1 on 2026-09-24 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('research_projects', '0005_workplanmilestone_deliverable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_end_date', models.DateField(editable=False)),
                ('requested_end_date', models.DateField()),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Endorsement'), ('endorsed', 'Endorsed'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('endorsed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests_endorsed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='research_projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
