# Generated by Django 6.1.1 on 2026-10-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_evaluationcriterion_evaluationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermreport',
            name='objective_accomplishments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
