# Generated by Django 6.1.1 on 2026-09-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenseRankedPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('work_type', models.CharField(help_text='e.g. digital art, literary work, software, multimedia', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField()),
                ('is_registered', models.BooleanField(default=False, help_text='Rights/ownership registration status')),
                ('rights_holder', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creative_works', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_works', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creative_works_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_creators', models.CharField(blank=True, help_text='Comma-separated names of other creators, if any', max_length=300)),
                ('title', models.CharField(max_length=400)),
                ('ip_type', models.CharField(choices=[('patent', 'Patent'), ('utility_model', 'Utility Model'), ('industrial_design', 'Industrial Design'), ('trademark', 'Trademark')], max_length=20)),
                ('status', models.CharField(choices=[('disclosed', 'Disclosed'), ('filed', 'Filed'), ('registered', 'Registered'), ('adopted', 'Adopted by a Recipient Community')], default='disclosed', max_length=20)),
                ('trl', models.PositiveSmallIntegerField(blank=True, help_text='Technology Readiness Level, 1-9', null=True)),
                ('is_commercialization_intended', models.BooleanField(default=False)),
                ('is_adopted_by_community', models.BooleanField(default=False)),
                ('adoption_moa_reference', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('registered_on', models.DateField(blank=True, null=True)),
                ('incentive_claimed', models.BooleanField(default=False, help_text='Incentive is given only once per patent/utility model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_records', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_records', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_records', to='research_projects.study')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('publication_type', models.CharField(choices=[('journal_article', 'Journal Article'), ('book', 'Book'), ('book_chapter', 'Book Chapter'), ('conference_proceeding', 'Conference Proceeding'), ('instructional_material', 'Instructional Material (Workbook/Module/Manual)')], max_length=30)),
                ('indexing_tier', models.CharField(blank=True, choices=[('isi', 'ISI-indexed (Web of Science / Clarivate)'), ('scopus', 'Scopus-indexed'), ('lspu_refereed', 'LSPU Refereed Research Journal'), ('non_indexed', 'Not Indexed')], max_length=20)),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('h_index', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_isbn', models.BooleanField(default=False)),
                ('is_lspu_published', models.BooleanField(default=False)),
                ('is_thesis_derived', models.BooleanField(default=False)),
                ('is_supervised_approved_thesis', models.BooleanField(default=False, help_text="Thesis/dissertation was an integral part of a duly approved R&D P/P/S under the author's supervision")),
                ('publisher_name', models.CharField(blank=True, max_length=200)),
                ('doi_or_isbn', models.CharField(blank=True, max_length=100)),
                ('published_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications_recorded', to=settings.AUTH_USER_MODEL)),
                ('study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='research_projects.study')),
                ('sense_publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='outputs.senserankedpublisher')),
            ],
        ),
    ]
