# Generated by Django 6.1.1 on 2026-09-24 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0001_initial'),
        ('research_projects', '0005_workplanmilestone_deliverable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('publications', 'Publications'), ('patents', 'Patents / IP'), ('products', 'Products'), ('people_services', 'People Services'), ('places_partnerships', 'Places and Partnerships'), ('policies', 'Policies')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('target_count', models.PositiveIntegerField(default=1)),
                ('manual_actual_count', models.PositiveIntegerField(default=0, help_text='Used for products/people/places/policies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_outputs', to='research_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('outcome', 'Outcome'), ('impact', 'Impact')], max_length=10)),
                ('description', models.TextField()),
                ('observed_on', models.DateField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, help_text='Where this is documented (report, MOA, news, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='research_projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcomes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
