# Generated by Django 6.1.1 on 2026-10-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outputs', '0002_expectedoutput_projectoutcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedoutput',
            name='description',
            field=models.TextField(),
        ),
    ]
