# Generated by Django 6.1.1 on 2026-09-22 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItemBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('certified', 'Certified')], default='draft', max_length=20)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certified_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='research_projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ps', 'Personal Services'), ('mooe', 'Maintenance and Other Operating Expenses'), ('co', 'Capital Outlay')], max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_app_flagged', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='budget_lib.lineitembudget')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lineitembudget',
            constraint=models.UniqueConstraint(fields=('project', 'version_number'), name='unique_project_budget_version'),
        ),
    ]
