# Generated by Django 6.1.1 on 2026-09-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='funding_source',
            field=models.CharField(blank=True, help_text='e.g. LSPU GAA, DOST-PCAARRD, LGU', max_length=150),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='is_counterpart',
            field=models.BooleanField(default=False, help_text='Counterpart (institutional share) funding'),
        ),
    ]
