# Generated by Django 6.1.1 on 2026-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_lib', '0002_lineitem_fiscal_year_lineitem_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='q1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='q2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='q3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='q4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
