# Generated by Django 6.1.1 on 2026-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_lib', '0003_lineitem_q1_amount_lineitem_q2_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('unit', 'unit'), ('month', 'month'), ('lump_sum', 'lump sum'), ('pax', 'pax'), ('lot', 'lot'), ('set', 'set'), ('hr', 'hr')], max_length=10),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
