# Generated by Django 6.1.1 on 2026-10-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_lib', '0004_line_item_unit_qty_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
