# Generated by Django 6.1.1 on 2026-09-23 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('metric_key', models.CharField(choices=[('output_score', 'Research Output Volume (publications + IP + creative works)'), ('compliance_score', 'Compliance Completeness (ethics review clearance rate)'), ('budget_utilization_pct', 'Budget Utilization %'), ('monitoring_health', 'Monitoring/Reporting Health'), ('renewal_eligible', 'Renewal Eligibility'), ('overrun_risk_inverse', 'Forecast Overrun-Risk (inverse — no risk scores higher)')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AHPMatrixRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('weights', models.JSONField(blank=True, default=dict, help_text='{criterion_id: normalized weight}, set on finalize')),
                ('consistency_ratio', models.FloatField(blank=True, null=True)),
                ('is_consistent', models.BooleanField(blank=True, help_text='True when consistency_ratio <= 0.10', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ahp_runs', to=settings.AUTH_USER_MODEL)),
                ('criteria', models.ManyToManyField(related_name='ahp_runs', to='decision_support.decisioncriterion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingRecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('funding_type_filter', models.CharField(blank=True, max_length=20)),
                ('campus_filter', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ahp_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_runs', to='decision_support.ahpmatrixrun')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AHPPairwiseComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Saaty scale 1/9-9')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='decision_support.ahpmatrixrun')),
                ('criterion_col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decision_support.decisioncriterion')),
                ('criterion_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='decision_support.decisioncriterion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'criterion_row', 'criterion_col'), name='unique_ahp_pair_per_run')],
            },
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_scores', models.JSONField(default=dict, help_text='{criterion_id: raw computed value}')),
                ('normalized_scores', models.JSONField(default=dict, help_text='{criterion_id: min-max normalized 0-1}')),
                ('composite_score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_scores', to='research_projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='decision_support.fundingrecommendationrun')),
            ],
            options={
                'ordering': ['rank'],
                'constraints': [models.UniqueConstraint(fields=('run', 'project'), name='unique_project_score_per_run')],
            },
        ),
    ]
