# Generated by Django 6.1.1 on 2026-09-24 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_support', '0001_initial'),
        ('research_projects', '0005_workplanmilestone_deliverable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisioncriterion',
            name='metric_key',
            field=models.CharField(choices=[('output_score', 'Research Output Volume (publications + IP + creative works)'), ('compliance_score', 'Compliance Completeness (ethics review clearance rate)'), ('budget_utilization_pct', 'Budget Utilization %'), ('monitoring_health', 'Monitoring/Reporting Health'), ('renewal_eligible', 'Renewal Eligibility'), ('overrun_risk_inverse', 'Forecast Overrun-Risk (inverse — no risk scores higher)'), ('risk_score_inverse', 'Project Risk Score (inverse of the 5x5 early-warning score)')], max_length=30),
        ),
        migrations.CreateModel(
            name='DecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('fund', 'Fund'), ('defer', 'Defer'), ('decline', 'Decline')], max_length=10)),
                ('indicative_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, help_text='e.g. BOR resolution / memo number', max_length=100)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_decisions', to='research_projects.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='decision_support.fundingrecommendationrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'project'), name='unique_decision_per_run_project')],
            },
        ),
    ]
