# Generated by Django 6.1.1 on 2026-09-23 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_projects', '0002_project_campus_project_cooperating_agencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('months_of_history', models.PositiveIntegerField(default=0)),
                ('arima_order', models.CharField(blank=True, help_text='(p, d, q) used to fit the model', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('insufficient_data', 'Insufficient Data'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('mae', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mape', models.DecimalField(blank=True, decimal_places=2, help_text='Mean Absolute Percentage Error', max_digits=6, null=True)),
                ('approved_budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_to_date', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('projected_total_at_horizon', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_overrun_risk', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='research_projects.project')),
                ('run_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=14)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.forecastrun')),
            ],
            options={
                'ordering': ['period'],
            },
        ),
    ]
